[package]
description = "Interact with the github.com/containers/image library via skopeo"
edition = "2018"
license = "MIT OR Apache-2.0"
name = "containers-image-proxy"
readme = "README.md"
repository = "https://github.com/containers/containers-image-proxy-rs"
version = "0.4.0"

[dependencies]
anyhow = "1.0"
capctl = "0.2.0"
fn-error-context = "0.2.0"
futures-util = "0.3.13"
lazy_static = "1.4.0"
nix = "0.22.0"
libc = "0.2"
serde = { features = ["derive"], version = "1.0.125" }
serde_json = "1.0.64"
semver = "1.0.4"
tokio = { features = ["full"], version = "1" }
tracing = "0.1"

[lib]
path = "src/imageproxy.rs"

[features]
proxy_v0_2_3 = []
