[package]
description = "Interact with the github.com/containers/image library via skopeo"
edition = "2018"
license = "MIT OR Apache-2.0"
name = "containers-image-proxy"
readme = "README.md"
repository = "https://github.com/cgwalters/containers-image-proxy"
version = "0.1.0"

[dependencies]
anyhow = "1.0"
fn-error-context = "0.2.0"
futures-util = "0.3.13"
lazy_static = "1.4.0"
nix = "0.22.0"
serde = { features = ["derive"], version = "1.0.125" }
serde_json = "1.0.64"
semver = "1.0.4"
tokio = { features = ["full"], version = "1" }
tokio-stream = "0.1.5"
tokio-util = { features = ["io"], version = "0.6" }
tracing = "0.1"

[package.metadata.docs.rs]
features = ["dox"]

[lib]
path = "src/imageproxy.rs"

